//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmyTechApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Applicant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Applicant()
        {
            this.ApplicantApplicationsFields = new HashSet<ApplicantApplicationsField>();
            this.ApplicantQualifications = new HashSet<ApplicantQualification>();
        }
    
        public int ID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
       
        public Nullable<System.DateTime> BirthDate { get; set; }
        [Required,RegularExpression("(01)[0-2]{1}[0-9]{8}", ErrorMessage ="Not Valid Number")]
        public string MobileNo { get; set; }
        [Required,RegularExpression("[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,64}",ErrorMessage ="Not Valid Email")]
        public string EMail { get; set; }

        public Nullable<int> GenderId { get; set; }
    
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicantApplicationsField> ApplicantApplicationsFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicantQualification> ApplicantQualifications { get; set; }
    }
}
