//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmyTechApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificationSpecific
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CertificationSpecific()
        {
            this.ApplicantQualifications = new HashSet<ApplicantQualification>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> CertificationTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicantQualification> ApplicantQualifications { get; set; }
        public virtual CertificationType CertificationType { get; set; }
    }
}
